require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'coverage/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

# Style preferences
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false  # We'll add YARD docs gradually

Style/FrozenStringLiteralComment:
  Enabled: true

# Metrics - adjust as needed
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# RSpec specific
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5
